metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "lmdb"

# Mode satu node (tanpa replikasi)
replication_mode = "none"
compression_level = 1

# Jaringan internal Garage
rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
# Ganti string di bawah dengan string acak buatan Anda sendiri
rpc_secret = "bWFza3VyZ2FyYWdlc2VjcmV0MTIzNDU2Nzg5MDEyMzQ="

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:9000"
root_domain = ".s3.garage.localhost"


[s3_web]
bind_addr = "[::]:9002"
root_domain = ".web.garage.localhost"

[admin]
api_bind_addr = "[::]:9001"